### ISSUE TITLE
HTTPS on your project website

### ISSUE THREAD

**Issue by rugk** [theupdateframework/theupdateframework.github.io#4]
It would be nice if you could add HTTPS support to http://theupdateframework.com.

There are some free CAs you can use. With [Let's Encrypt](https://letsencrypt.org/) you can e.g. make it automated.

for what it's worth even if the user wants to access the GitHub page manually at https://theupdateframework.github.io/ he/she gets redirected which I think is not a good thing to do if the redirection ends up on a http site.

**Comment by JustinCappos** [comment]
Thanks for pointing this out.  Our IT staff made an error which we did not
notice.  It should be corrected now.

Justin

**Comment by rugk** [comment]
A now the redirection is the other way around. From http://theupdateframework.com/ to https://theupdateframework.github.io/.

I think that's a good way to do this. So I close this issue as it's fixed.
