### ISSUE TITLE
Decommission this repo

### ISSUE THREAD

**Issue by lucperkins** [theupdateframework/theupdateframework.github.io#51]
As the site is now being published on Netlify and from different sources, this repo is no longer necessary and can be either archived or removed.

cc @lukpueh

**Comment by lukpueh** [comment]
I wouldn't completely remove the GitHub page. I just grepped through some of our TUF resources and saw that we have many pointers to `theupdateframework.github.io`. We can change those, but it's likely that others used that URL too (`theupdateframework.com` just redirected to `theupdateframework.github.io`, so browser URL bars always showed the latter).

We could try to add a client side redirect here (Jekyll even has an [extension for that](https://github.com/jekyll/jekyll-redirect-from#redirect-to)). Or, we continue to host the new page here ([Hugo has instructions](https://gohugo.io/hosting-and-deployment/hosting-on-github/#github-user-or-organization-pages) for how to do that using git submodules).

Let me know what you think, @lucperkins.

**Comment by lucperkins** [comment]
@lukpueh The solution in #52 looks good to me. I'll close this issue in favor of your approach.
